spring:
  config:
    import:
      - classpath:tg-credentials.yml
  main:
    banner-mode: "off"

logging:
  level:
    com.softpunk: DEBUG

app:
  localization:
    path: "./common/localization/src/main/resources/locales.json"
  session:
    limit: 100
    defaultLocale: "ru"