spring:
  config:
    import:
      - classpath:tg-credentials.yml
      - classpath:database.yml
  main:
    banner-mode: "off"

logging:
  level:
    com.softpunk: DEBUG

app:
  localization:
    path: "./common/localization/src/main/resources/locales.json"
  session:
    limit: 100
    defaultLocale: "ru"
  pagination:
    pageSize: 5
  schedule:
    maxIntervalMinutes: 90
  states:
    statesSizeToBackButton: 5
  useMainMenuButton: true
  notifier:
    enable: true
    periodMs: 10000
    minDelayMs: 20000
    maxDelayMs: 40000